<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>zeusTestSuits</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ea9b20f5-ecc2-49b6-bfba-aa81092352d9</testSuiteGuid>
   <testCaseLink>
      <guid>ac83b4ca-b1b2-4663-861a-5ab098dd4340</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/getAccountInfo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>938db112-b331-4f87-9fcc-708463e2a2a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e00a0406-b639-430e-a704-b075389b32ef</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
